### ISSUE TITLE
Export all playlists into one excel file

### ISSUE THREAD

**Issue by rosettadp** [pavel-aicradle/exportify#18]
Hello,
Is there a way when exporting all playlists to export into one large file?
I have over 300 plus playlists and to do this manually takes way too much time.
Hoping someone could guide me on if this is possible.
Thanks

**Comment by pavel-aicradle** [comment]
If you "Export All", then they should all end up in a zip file. Yeah, with that many playlists, it will spin for a good long time before the download starts. But unfortunately due to Spotify's rate limits, that's just a something we have to deal with.

Once it's down, it is possible to iterate through and concatenate all the .csvs programmatically using the language of your choice. I'd do it with Python and pandas myself.

**Comment by rosettadp** [comment]
Ok thank you. How difficult would it be for there to be another column in the excel (CSV file) that included the name of the playlist?

**Comment by pavel-aicradle** [comment]
Not hard, but you'd be duplicating that information across every single row of the table. It's not something I'd consider adding to this web app, but you can do it in post-processing.
